#CH-231-A
#a11
#Timofei Podkorytov
#tpodkoryto@jacobs-university.de
#tpodkoryto@constructor.university
p1: HashTable.h HashTable.cpp run.cpp
	g++ -Wall -o p1 run.cpp HashTable.h HashTable.cpp
runp1:
	./p1