p1make: a1.cpp
	g++ -o a1 a1.cpp 
p2make: Stack.h testStack.cpp
	g++ -o a2 Stack.h testStack.cpp
p3make: LinkedList.h testLinkedList.cpp
	g++ -o a3 LinkedList.h testLinkedList.cpp
p4make: a4.cpp
	g++ -o a4 a4.cpp 
p5make: a5.cpp
	g++ -o a5 a5.cpp 
p1run:
	./a1
p2run:
	./a2
p3run:
	./a3
p4run:
	./a4
p5run:
	./a5
all: a1.cpp Stack.h testStack.cpp LinkedList.h testLinkedList.cpp a4.cpp a5.cpp
	g++ -o a1 a1.cpp 
	g++ -o a2 Stack.h testStack.cpp
	g++ -o a3 LinkedList.h testLinkedList.cpp
	g++ -o a4 a4.cpp 
	g++ -o a5 a5.cpp 