#CH-231-A
#a9
#Timofei Podkorytov
#tpodkoryto@jacobs-university.de
#tpodkoryto@constructor.university
p1make: p1.cpp
	g++ -Wall -o p1 p1.cpp
p2make: p2.cpp
	g++ -Wall -o p2 p2.cpp
p1run:
	./p1
p2run:
	./p2