p1make: a1.cpp
	g++ -Wall -o a1 a1.cpp 
p2make: a2.cpp
	g++ -Wall -o a2 a2.cpp 
p3make: WindGauge.h WindGauge.cpp testWindGauge.cpp
	g++ -Wall -o a3 WindGauge.h WindGauge.cpp testWindGauge.cpp
p4make: a4.cpp 
	g++ -Wall -o a4 a4.cpp 
p5make: a5.cpp 
	g++ -Wall -o a5 a5.cpp 
p6make: a6.cpp 
	g++ -Wall -o a6 a6.cpp 
p1run:
	./a1
p2run:
	./a2
p3run:
	./a3
p4run:
	./a4
p5run:
	./a5
p6run:
	./a6
all: a1.cpp a2.cpp WindGauge.h WindGauge.cpp testWindGauge.cpp a4.cpp a5.cpp a6.cpp 
	g++ -Wall -o a1 a1.cpp 
	g++ -Wall -o a2 a2.cpp 
	g++ -Wall -o a3 WindGauge.h WindGauge.cpp testWindGauge.cpp
	g++ -Wall -o a4 a4.cpp 
	g++ -Wall -o a5 a5.cpp 
	g++ -Wall -o a6 a6.cpp 