#CH-231-A
#a8
#Timofei Podkorytov
#tpodkoryto@jacobs-university.de
#tpodkoryto@constructor.university
p1abmake: countBucket.cpp
	g++ -Wall -o p1ab countBucket.cpp
p1dmake: wordSort.cpp
	g++ -Wall -o p1d wordSort.cpp
p2make: origRadixSort.cpp
	g++ -Wall -o p2 origRadixSort.cpp
p1abrun:
	./p1ab
p1drun:
	./p1d
p2run:
	./p2
